require:
  - rubocop-performance
  - rubocop-rspec

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - webmention-cli.gemspec
    - spec/**/*.rb

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
