require:
  - rubocop-performance
  - rubocop-rspec

Layout/AlignHash:
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - webmention-cli.gemspec
    - spec/**/*.rb

Metrics/LineLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/webmention-cli.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
