require:
  - rubocop-performance
  - rubocop-rspec

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - webmention-cli.gemspec
    - spec/**/*.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
